services:
  - type: web
    name: pdiot-cw3
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: NORMALIZE
        value: "true"
      - key: INPUT_WINDOW
        value: "128"
      - key: INPUT_DIM
        value: "3"
      - key: LABELS
        value: "ascending,descending,lyingBack,lyingLeft,lyingRight,lyingStomach,miscMovement,normalWalking,running,shuffleWalking,sittingStanding"
